#!/usr/bin/env python3
"""Generate TVPMessages.decl.h from script/messages.json."""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path


def cpp_escape(text: str) -> str:
    return (
        text.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\r", "\\r")
        .replace("\n", "\\n")
        .replace("\t", "\\t")
    )


def wrap_message_line(name: str, text: str) -> str:
    escaped = cpp_escape(text)
    return f'TVP_MSG_DEFINE({name}, "{escaped}")'


def generate_decl(messages: list[dict]) -> str:
    header = f"""// Generated by {os.path.basename(__file__)} from messages.json. Do not edit.
#ifndef TVP_MESSAGES_DECL_H_
#define TVP_MESSAGES_DECL_H_

// Define TVP_MSG_DEFINE before including this file.

"""
    body_lines = [wrap_message_line(item["id"], item["text"]) for item in messages]

    footer = "\n#endif\n"
    return header + "\n".join(body_lines) + footer


def main() -> int:
    if len(sys.argv) != 2:
        print(f"usage: {os.path.basename(__file__)} <output.decl.h>", file=sys.stderr)
        return 1

    script_dir = Path(__file__).resolve().parent
    json_path = script_dir / "messages.json"
    output_path = Path(sys.argv[1]).resolve()

    with json_path.open(encoding="utf-8") as f:
        data = json.load(f)

    messages = data.get("messages", [])
    if not messages:
        print(f"error: no messages in {json_path}", file=sys.stderr)
        return 1

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8", newline="\n") as out:
        out.write(generate_decl(messages))
    print(f"create file: {output_path} ({len(messages)} messages)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
